package ru.oparin.solution.model;

public enum WbApiEventType {
    CONTENT_CARDS_LIST_PAGE,
    ANALYTICS_SALES_FUNNEL_NMID,
    PRICES_PRODUCTS_BATCH,
    PRICES_SPP_ORDERS,
    PROMOTION_COUNT,
    PROMOTION_ADVERTS_BATCH,
    PROMOTION_STATS_BATCH,
    FEEDBACKS_SYNC_CABINET,
    PROMOTION_CALENDAR_SYNC_CABINET,
    WAREHOUSES_SYNC_CABINET,
    STOCKS_BY_NMID
}
